### PR TITLE
Ipfs cluster integration

### PR DESCRIPTION
**Pull request by farhoud**

### CODE REVIEW

**Comment by farhoud** [comment]
Oh warning!
I will fix the react-todo-app type warning.

**Comment by gitaaron** [comment]
- [ ] fula client connect should support both string and string[] for backwards compatibility

- [ ] secret setup
           * primary method did not work on osx
           * offer one cmd that works on any dev machine

- [ ] secret setup + docker-compose only works with two Boxes
          * no need to have Box0 and Box1 services
          * just run docker-compose twice

- [ ] ideally we can come up with a way so that we don't have to call docker-compose down
           * separate config service that is dependency of other services?

- [ ] fula client should not connect to Boxes over pnet
        * Boxes connect to each other over pnet

**Comment by farhoud** [comment]
>     * [ ]  fula client should not connect to Boxes over pnet
>       * Boxes connect to each other over pnet

I don't think its possible until security layer integrated. So please put it out of scope of this PR

**Comment by farhoud** [comment]
> * secret setup + docker-compose only works with two Boxes
>       * no need to have Box0 and Box1 services
>       * just run docker-comp 

I don't think this is part of this PR.

**Pull request merged**
